### ISSUE TITLE
Add method to click on p:selectOneButton

### ISSUE THREAD

**Issue by krichter722** [omnifaces/arquillian-primefaces#5]
It'd be nice to have a method to be able to click on a specified option of a `p:selectOneButton`.

**Comment by krichter722** [comment]
Awesome! Thank you so much!

**Comment by krichter722** [comment]
`p:selectOneButton` can be added to `README.md` as well (maybe other things were added as well?).

**Comment by BalusC** [comment]
Sure, when 0.3 is released.
