### ISSUE TITLE
org.openqa.selenium.TimeoutException:  Expected condition failed: waiting for at least one condition to be valid: visibility of GrapheneElement -> GrapheneElement -> GrapheneElement -> [[[[[[ChromeDriver: chrome on LINUX (452db23774a778c440389680d4c27a98)] -> id: offerForm:offerDialogOfferTypeAutoComplete]] -> xpath: /*]] -> id: offerForm:offerDialogOfferTypeAutoComplete_panel] || value to contain "ui-state-error". Current value: "null"

### ISSUE THREAD

**Issue by krichter722** [omnifaces/arquillian-primefaces#9]
I'm experiencing

```
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for at least one condition to be valid: visibility of GrapheneElement -> GrapheneElement -> GrapheneElement -> [[[[[[ChromeDriver: chrome on LINUX (452db23774a778c440389680d4c27a98)] -> id: offerForm:offerDialogOfferTypeAutoComplete]] -> xpath: /*]] -> id: offerForm:offerDialogOfferTypeAutoComplete_panel] || value to contain "ui-state-error". Current value: "null" (tried for 15 second(s) with 500 milliseconds interval)
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'richter-Lenovo-IdeaPad-Z500', ip: '192.168.178.34', os.name: 'Linux', os.arch: 'amd64', os.version: '4.13.0-38-generic', java.version: '1.8.0_162'
Driver info: org.openqa.selenium.chrome.ChromeDriver$$EnhancerByGraphene$$d8df1c7f
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.37.544315 (730aa6a5fdba15..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 65.0.3325.181, webStorageEnabled: true}
Session ID: 452db23774a778c440389680d4c27a98
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:81)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:271)
	at org.jboss.arquillian.graphene.wait.WebDriverWaitImpl.until(WebDriverWaitImpl.java:96)
	at org.omnifaces.utils.arquillian.ArquillianPrimeFaces.setAutoCompleteQuery(ArquillianPrimeFaces.java:333)
[...]
```

with `chormeheadless`, `chrome`, `firefox` and `phantomjs` drivers. I tried to isolate a SSCCE for 4 hours now, without a lot of progress (it's a > 250 classes, > 25 pages project), so I was wondering whether you could take a look at the stacktrace and the code. I'll continue the attempt to extract a SSCCE if you can't or don't want to. The `p:autoComplete` is inside a `p:dataTable` which is inside a `p:dialog` which is `ui:include`d in a template.

**Comment by BalusC** [comment]
Have you tried setting `ArquillianPrimeFaces#configureTimeout()` higher? You can do this in a `@Before` method. It defaults to 2\~3 seconds which is too low when the build machine is busy and/or when the `completeMethod()` takes too much time. Try 5\~10 seconds and/or profiling and fixing the slowness of code behind `completeMethod()`.

**Comment by krichter722** [comment]
> Have you tried setting ArquillianPrimeFaces#configureTimeout() higher? You can do this in a @Before method.

Thanks for the tips. I set it to 15 seconds right before invoking `ArquillianPrimeFaces.setAutoCompleteQuery` (since I had trouble once with the sequence of JUnit methods and Arquillian test runner) which should do the job, right?

I'm about to finish the SSCCE.

**Comment by krichter722** [comment]
I provided a SSCCE at https://gitlab.com/krichter/arquillian-primefaces-auto-complete-set-query-2 which shows the issue occuring even with 30 seconds timeout. I hope that helps you to clarify this issue, thanks in advance.

**Comment by krichter722** [comment]
In the same environment `ArquillianPrimeFaces.setSelectOneMenuValue` (for a `p:selectOneMenu`) seems to have no effect.

**Comment by BalusC** [comment]
Try increasing the screen size via WebDriver. Chances are that the dialog
and/or panel flows outside the viewport and therefore Selenium cannot "see"
it.

**Comment by krichter722** [comment]
`p:selectOneMenu` is fixed, now, I guess by ba6b61918ebe35bb795cead5c5138955c07779ae which is probably unrelated to this issue. Thank you.

> Try increasing the screen size via WebDriver. Chances are that the dialog and/or panel flows outside the viewport and therefore Selenium cannot "see" it.

I've been running it with `chrome`, `phantomjs` on a large screen (1650x1050) as well as with `chromeheadless` with `<property name="chromeArguments">--no-sandbox --window-size=1920,1080</property>`. Running on my screen shows that sizing can't be the issue.

**Comment by BalusC** [comment]
I couldn't get your project to run (Maven couldn't find web project for unclear reason), so I added an IT which wraps the form in a dialog and it works just fine. 

Only for phantomjs I had indeed to increase screensize.
```
@Before
public void init() {
	browser.manage().window().setSize(new Dimension(1600, 1200)); // Necessary to get the form in the dialog to fit within the viewport.
	// ...
}

```

**Comment by krichter722** [comment]
> I couldn't get your project to run (Maven couldn't find web project for unclear reason), so I added an IT which wraps the form in a dialog and it works just fine.

Sorry for that. I added a `.gitlab-ci.yml` which showed that it needed a `repository`. You can try it locally now or investigate the CI log at https://gitlab.com/krichter/arquillian-primefaces-auto-complete-set-query-2/pipelines/20527462.

**Comment by BalusC** [comment]
I see that you used chromeheadless. Have you tried htmlunit/phantomjs?

As explained in https://github.com/omnifaces/arquillian-primefaces/pull/11, chromeheadless has more issues.

**Comment by krichter722** [comment]
> I see that you used chromeheadless. Have you tried htmlunit/phantomjs?

Good point. Unfortunately, all three of chromeheadless, phantomjs and htmlunit fail, see https://gitlab.com/krichter/arquillian-primefaces-auto-complete-set-query-2/pipelines/20536017 for details. The htmlunit failure and preceeding error messages are different, though.

**Comment by BalusC** [comment]
I ran it and it turns out that it indeed didn't unfold the panel at all because the complete method returned an empty list. `ArquillianPrimeFaces#setAutoCompleteQuery()` expected that either a panel is to be shown, or that the autocomplete shows a validation error. But none of these conditions happened.

What use case exactly are you trying to test? A non-existent query without a panel or a validation error? Wouldn't you rather show a validation error here?

**Comment by krichter722** [comment]
> What use case exactly are you trying to test? A non-existent query without a panel or a validation error? Wouldn't you rather show a validation error here?

Sorry, I don't understand what you mean by "without a panel". I was testing that entering an arbitrary string into the `p:autoComplete` which matches no auto-completion item, doesn't cause a value to be set on `p:autoComplete`'s `value` (together with further interaction past `setQuery` which makes this a valid test case, i.e. I'm not testing PrimeFaces functionality here).

BTW, I changed the SSCCE slightly to avoid re-opening the dialog after update which is less intuitive than updating the panel.

**Comment by BalusC** [comment]
With the panel I'm referring to the panel containing the auto completion items.

The `ArquillianPrimeFaces#setAutoCompleteQuery()` waits for the following two conditions after the query is typed:
1. The panel with select items is shown.
2. Or, the input is marked invalid.

However, none of both has happened within the timeout. Hence the exception.

I can adjust the `setAutoCompleteQuery()` to match your use case, but I'm wondering why you didn't trigger a validation error when no items are found. If you were the enduser, what would you expect the web application to do? Currently, it appears to give no feedback whatsoever when you enter an invalid query. Wouldn't that be confusing to you as being the enduser?

**Comment by krichter722** [comment]
> I can adjust the setAutoCompleteQuery() to match your use case, but I'm wondering why you didn't trigger a validation error when no items are found. If you were the enduser, what would you expect the web application to do? Currently, it appears to give no feedback whatsoever when you enter an invalid query. Wouldn't that be confusing to you as being the enduser?

That'd be awesome. Also, thanks for you feedback. The idea back then was to validate with `Validator.validate` in the backing bean with different validation groups which I didn't seem to manage with the latest Primefaces 5.x and JSF 2.0. This may have changed meanwhile, but it's a running system which I could change to be testable, but only as a last resort. The constraint violoations are then transformed into a message and send to a `p:messages`.

**Comment by BalusC** [comment]
I still don't clearly understand how exactly you're informing the user about a validation error. Just the presence of a p:message associated with p:autoComplete? 

In that case I suggest to simply add a single line to your current code which adds that message, to also set `component.setValid(false)` on the autocomplete component. Because, that's what the system should really have been doing. Then the IT will pass happily.

**Comment by krichter722** [comment]
> I still don't clearly understand how exactly you're informing the user about a validation error. Just the presence of a p:message associated with p:autoComplete?

No, the `p:messages` is empty initially and the message is constructed in the backing bean and send to `p:messages` with `FacesContext.addMessage`. It'd require a lot of change to work around that in order to make the test work.

**Comment by BalusC** [comment]
So, the end user doesn't get any feedback that the query is invalid?

**Comment by krichter722** [comment]
> So, the end user doesn't get any feedback that the query is invalid?

Yes, there's no feedback until submission. I might take a look at that in my project. However, it makes sense to support this case in arquillian-primefaces or cover this case in the docs.

**Comment by BalusC** [comment]
I've added an overloaded `setAutoCompleteQuery()` method and clarified the javadocs.

In your specific case, use

```
ArquillianPrimeFaces.setAutoCompleteQuery(autoComplete, query, false);
